/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package indexpage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author reena
 */
public class NewProduct extends javax.swing.JFrame {
    int idno;
    ResultSet rs;
    public void data()
    {
        try
        {
              Class.forName("com.mysql.cj.jdbc.Driver");
              
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/datademo","root","");
            Statement stm = con.createStatement();
            
            rs = stm.executeQuery("select * from stocks");
            
//            if(rs.next())                      // used for showing data directly
//            {
//                sp.setText(rs.getInt(4)+"");
//                nm.setText(rs.getString(2)+"");
//                pp.setText(rs.getInt(3)+"");
//            }
//            else{
//                this.setVisible(false);
//            }
           
            
        
        }
        catch (Exception e)
        {
            System.out.print(e);
        }
    }
    
    /**
     * Creates new form NewProduct
     */
    public NewProduct() {
        initComponents();
        setSize(500,500);
        data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nm = new javax.swing.JTextField();
        pp = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        upd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        sp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nm.setText("Product Name");
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        getContentPane().add(nm);
        nm.setBounds(120, 50, 110, 40);

        pp.setText("Purchase Price");
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        getContentPane().add(pp);
        pp.setBounds(120, 100, 110, 40);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(150, 200, 72, 22);

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 20, 72, 22);

        upd.setText("update");
        upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updActionPerformed(evt);
            }
        });
        getContentPane().add(upd);
        upd.setBounds(380, 70, 72, 22);

        jLabel1.setText("product_id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 90, 30);

        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });
        getContentPane().add(id1);
        id1.setBounds(360, 20, 110, 30);

        sp.setText("Sales Price");
        getContentPane().add(sp);
        sp.setBounds(120, 150, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
    
    }//GEN-LAST:event_ppActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
    Masterpage.main(new String[2]);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
  
        String prodname = nm.getText();
        String prodprice = pp.getText();
        String salesprice = sp.getText();
        try{
            Connection con = InitConnection.initConn();
            PreparedStatement ps = con.prepareStatement("update product set p_Name=?, p_Price=?, s_Price=? where p_Id = "+idno);
            

            ps.setString(1, prodname);
            ps.setString(2, prodprice);
            ps.setString(3, salesprice);
            
            int x = ps.executeUpdate();
            JOptionPane.showMessageDialog(null , "data updated sucessfully");
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updActionPerformed
     String s =id1.getText();
         idno= Integer.parseInt(s);
         
         try{
             Connection con = InitConnection.initConn();
             Statement stm = con.createStatement();
             ResultSet rs= stm.executeQuery("select *from product where p_Id = "+idno);
             if(rs.next())
             {
                 nm.setText(rs.getString(2)+"");
                 pp.setText(rs.getString(3)+"");
                 sp.setText(rs.getString(4)+"");
                 
                 
             }
         }
         catch(Exception e){
             System.out.print(e);
         } // TODO add your handling code here:
    }//GEN-LAST:event_updActionPerformed

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField pp;
    private javax.swing.JButton save;
    private javax.swing.JTextField sp;
    private javax.swing.JButton upd;
    // End of variables declaration//GEN-END:variables
}
