/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package indexpage;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Vector;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author reena
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    int invno, id,p_id;
    Connection con = null;
    Vector v1 = null;
    Vector v2 = null;
    Vector v3 = null;
    Vector v4 = null;
    
    
    public void getData()
    {
        try{
            con = InitConnection.initConn();
            Statement stm = con.createStatement();
            //for invoice no
            ResultSet rs1 = stm.executeQuery("select inv_no from purchase");
            
            if(rs1.next())
            {
                invno = rs1.getInt(1);
                while(rs1.next())
                {
                    invno= rs1.getInt(1);
                }
                invno = invno+1;
            }
            else
            {
                invno = 101;
            }
            inv.setText(invno+"");
            
            // Query for customer data
            ResultSet rs2 = stm.executeQuery("select Id, Name, City,Address, Mobile_no, Status FROM customer");
            v1 = new Vector();
            v2 = new Vector();
            while(rs2.next())
            {
                v1.addElement(rs2.getInt(1));        // purchase wali table me customer id yha se jaygi
                custcombobox.addItem(rs2.getString(2));
                v2.addElement(rs2.getString(3));
            }
            
            ResultSet rs3 = stm.executeQuery("select p_Id, p_Name, p_Price, s_Price from product where p_Status = 0");
            
            v3 = new Vector();
            v4 = new Vector();
            
            while(rs3.next())
            {
                v3.addElement(rs3.getInt(1));
                prodcombobox.addItem(rs3.getString(2));
                v4.addElement(rs3.getInt(3));
            }


        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }
    
    public Purchase() {
        initComponents();
        setSize(700,800);
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inv = new javax.swing.JTextField();
        custcombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prodcombobox = new javax.swing.JComboBox<>();
        cty = new javax.swing.JTextField();
        pp = new javax.swing.JTextField();
        pq = new javax.swing.JTextField();
        ta = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        save = new javax.swing.JButton();
        total = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        inv.setText("Invoice no.");
        inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invActionPerformed(evt);
            }
        });
        getContentPane().add(inv);
        inv.setBounds(6, 17, 80, 30);

        custcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custcomboboxItemStateChanged(evt);
            }
        });
        custcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custcomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(custcombobox);
        custcombobox.setBounds(296, 17, 72, 22);

        jLabel1.setText("Customer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(206, 17, 69, 22);

        jLabel2.setText("Product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(206, 57, 69, 22);

        prodcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                prodcomboboxItemStateChanged(evt);
            }
        });
        prodcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodcomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(prodcombobox);
        prodcombobox.setBounds(296, 57, 72, 22);

        cty.setText("City");
        cty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctyActionPerformed(evt);
            }
        });
        getContentPane().add(cty);
        cty.setBounds(6, 57, 90, 30);

        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        getContentPane().add(pp);
        pp.setBounds(6, 134, 140, 31);
        getContentPane().add(pq);
        pq.setBounds(170, 140, 98, 28);

        ta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taActionPerformed(evt);
            }
        });
        getContentPane().add(ta);
        ta.setBounds(310, 130, 89, 40);

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(42, 215, 72, 22);

        save.setText("Submit");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(331, 215, 72, 22);

        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(180, 220, 80, 20);

        jLabel3.setText("Product Purchase Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 120, 16);

        jLabel4.setText("Product Quality");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 110, 100, 16);

        jLabel5.setText("Total Amount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 100, 100, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invActionPerformed
      
    }//GEN-LAST:event_invActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
    this.setVisible(false);
    Masterpage.main(new String[2]);    
    // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void custcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custcomboboxActionPerformed

    private void custcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custcomboboxItemStateChanged
                
         try
        {
            int x = custcombobox.getSelectedIndex();
            cty.setText((String)v2.get(x));
            id = (Integer)v1.get(x);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_custcomboboxItemStateChanged

    private void prodcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodcomboboxActionPerformed
         try
        {
            int x = prodcombobox.getSelectedIndex();
            pp.setText((Integer)v4.get(x)+"");
            p_id = (Integer)v3.get(x);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_prodcomboboxActionPerformed

    private void prodcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_prodcomboboxItemStateChanged
        try
        {
            int x = prodcombobox.getSelectedIndex();
            pp.setText((Integer)v4.get(x)+"");
            p_id = (Integer)v3.get(x);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_prodcomboboxItemStateChanged

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
     int x = Integer.parseInt(pp.getText());
        int y = Integer.parseInt(pq.getText());
        ta.setText((x*y)+"");
   // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     try
        {
            Connection con = InitConnection.initConn();
            PreparedStatement ps =  con.prepareStatement("insert into purchase(inv_no,c_id,p_id,p_price,p_qty,t_amt) values(?,?,?,?,?,?)");
            ps.setInt(1,Integer.parseInt(inv.getText()));
            ps.setInt(2,id);
            ps.setInt(3,p_id);
            ps.setInt(4, Integer.parseInt(pp.getText()));
            ps.setInt(5, Integer.parseInt(pq.getText()));
            ps.setInt(6, Integer.parseInt(ta.getText()));
            int x = ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"data updated succesfully");
            con.close();
           
        }
        catch(Exception e)
        {
            System.out.print(e);
                   
        }   // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppActionPerformed

    private void taActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taActionPerformed

    private void ctyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cty;
    private javax.swing.JComboBox<String> custcombobox;
    private javax.swing.JButton home;
    private javax.swing.JTextField inv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField pq;
    private javax.swing.JComboBox<String> prodcombobox;
    private javax.swing.JButton save;
    private javax.swing.JTextField ta;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
